{% set name = "nidaqmx-python" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ni/nidaqmx-python/archive/{{ version }}.tar.gz
  sha256: 56a9e072a0c97a7d99af5a3d21d8d5aeb41f49bfee4305ffb28eb2bc67da41ee

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8, <4.0
    - pip
    - poetry >=1.2
  run:
    - python >=3.8, <4.0
    - numpy >=1.22, <2.0
    - deprecation >=2.1

test:
  imports:
    - nidaqmx

about:
  home: https://github.com/ni/nidaqmx-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python API for interacting with NI-DAQmx
  description: |
    The nidaqmx package contains an API (Application Programming Interface) for
    interacting with the NI-DAQmx driver. The package is implemented in Python.
    This package was created and is supported by NI. The package is implemented
    as a complex, highly object-oriented wrapper around the NI-DAQmx C API using
     the ctypes Python library.
  doc_url: http://nidaqmx-python.readthedocs.io/en/latest/
  dev_url: https://github.com/ni/nidaqmx-python

extra:
  recipe-maintainers:
    - carlodri
    - lstebel
